config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users

  resources :items

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
  end

  root to: 'home#index'

  get "up" => "rails/health#show", as: :rails_health_check
#   get '*path', to: redirect('/'), constraints: lambda { |req|
#   req.path.exclude? 'rails/active_storage'
# }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true

  belongs_to :user, optional: true
  has_many :post_items, dependent: :destroy
  has_many :posts, through: :post_items
  has_one_attached :item_cover do |attachable|
    attachable.variant :small, resize_and_pad: [60, 60]
    attachable.variant :wardrobe, resize_and_pad: [100, 100]
    attachable.variant :full, resize_and_pad: [200, 200]
  end
  validates :item_cover, content_type: { in: [:png, :jpeg], spoofing_protection: true }
  validates :item_cover, size: { less_than: 5.megabytes }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :event, presence: true
  belongs_to :user
  has_many :post_items
  has_many :items, through: :post_items
  has_many :comments, dependent: :destroy

  has_many_attached :images
end

app/models/post_item.rb
class PostItem < ApplicationRecord
  belongs_to :item
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_fill: [48, 48]
    attachable.variant :medium, resize_to_fill: [200, 200]
  end
  validates :avatar, content_type: { in: [:png, :jpeg], spoofing_protection: true }
  validates :avatar, size: { less_than: 2.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protected

  def configure_permitted_parameters
    # Permit the username field for sign up
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    # Permit the username field for account update
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    @post = @comment.post
    if @comment.save
      redirect_to @post, notice: 'Posted'
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @post = @comment.post
    if @comment.destroy!
      redirect_to @post, notice:'Deleted'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = current_user.items.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, notice: "Item was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_item
      @item = Item.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.expect(item: [ :name, :description, :user_id, :item_cover ])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /items/new
  def new
    @post = Post.new
  end

  # GET /items/1/edit
  def edit
  end

  def index
    # Fetch all posts, ordered by creation date (newest first)
    @posts = Post.order(created_at: :desc)
  end

  # Optional: For showing a single post
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post was successfully deleted."
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Posted'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_post
    @post = Post.find(params.expect(:id))
  end

  def post_params
    params.require(:post).permit(:event, :description, :user_id, :post_item, item_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#    before_action :authenticate_user!
# skip_before_action :authenticate_user, %i[new, create]
  def own?(object)
    id == object&.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar.attached?
      image_tag user.avatar.variant(:thumb).processed, class: "rounded-circle"
    else
      image_tag 'IconU.png'
    end
  end
  def user_avatar_preview(user)
    if user.avatar.attached?
      image_tag user.avatar.variant(:medium).processed, class: "rounded-circle"
    else
      "NO AVATAR"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="flex items-center space-x-2 p-2 bg-gray-100 rounded-md">
    <div class= "shadow-2xl bg-gray-300 rounded-md">
      <% if comment.user.avatar.attached? %>
        <%= image_tag comment.user.avatar.variant(:thumb).processed, class: "ml-2 rounded-circle" %>
      <% else %>
        <%= image_tag "IconU.png", class: "rounded-circle", size: "48x48" %>
      <% end %>
      <span class="text-indigo-600 mr-2"><%= comment.user.name %></span>
    </div>
    <div class="h-8 w-px bg-gray-400"></div>
    <div class="comment-body">
      <p class="text-3xl"><%= comment.body %></p>
    </div>
  </div>
    <div class= "flex items-center space-x-2">
      <span class ="inline whitespace-nowrap"><%= "#{time_ago_in_words(comment.created_at)} ago" %></span>
      <div class="h-4 w-px bg-black"></div>
      <% if comment.user == current_user %>
        <span class= "inline whitespace-no wrap text-red-600 hover:text-red-950"><%= button_to "delete", comment, method: :delete %></span>
      <% end %>
    </div>
  </div>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
<%= simple_form_for [@post, @post.comments.build] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, "Comment", class: "rounded-lg" %>
<% end %>
</div>

app/views/home/index.html.erb
<div class="flex items-center justify-center h-screen w-full">
  <div class="flex gap-4">
    <nav class="flex gap-2">
      <%= button_to "Garb", items_path, method: :get, class: "px-10 py-30 md:px-30 md:py-30 lg:px-50 lg:py-50 xl:px-80 xl:py-80 text-lg font-semibold text-white bg-blue-600 rounded-lg hover:bg-blue-700" %>
      <%= button_to "Gab", posts_path, method: :get, class:"px-10 py-30 md:px-30 md:py-30 lg:px-50 lg:py-50 xl:px-80 xl:py-80 text-lg font-semibold text-white bg-gray-600 rounded-lg hover:bg-gray-700" %>
    </nav>
  </div>
</div>

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>

  <%= f.input :name, required: true, allow_blank: false%>

  <%= f.input :item_cover, as: :file, label: 'Image', hint: "Items with no image cannot be posted in Gabs" %>
  <br>
  <%= f.input :description %>

  <div class="form-actions">
    <%= f.button :submit, "Create", class: "rounded-lg" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class=" w-full sm:w-auto my-5 space-y-5">
  <div>
    <h1 class="font-bold text-4xl"><%= item.name %></h1>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= item.description %>
  </div>
</div>

app/views/items/edit.html.erb
<% content_for :title, "Editing item" %>

<div class="w-full">
<div class="w-auto sm:w-1/2 md:w-1/3 mx-auto">
  <h1 class="font-bold text-4xl">Editing item</h1>

  <%= render "form", item: @item %>

  <%= link_to "Show this item", @item, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to items", items_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>
</div>

app/views/items/index.html.erb
<% content_for :title, "Items" %>

<div class="w-full">
<div class="w-auto sm:w-1/2 md:w-1/3 mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex mt-1 justify-center items-center">
    <h1 class="font-bold text-4xl underline">Items</h1>
    <%= link_to "New item", new_item_path, class: "fixed inset-x-30 bottom-6 p-4 w-auto text-center rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>
<br>
<div class="image-grid mb-20">
  <% @items.each do |item| %>
    <%= link_to item_path(item) do %>
      <% if item.item_cover.attached? %>
        <%= image_tag item.item_cover.variant(:wardrobe).processed, class: "ring-1 grid-image" %>
      <% else %>
        <div class="box-border size-51 border-4 p-4 ring-1">
          <%= render item %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>
</div>
</div>

app/views/items/new.html.erb
<% content_for :title, "New item" %>

<div class="w-full">
<div class="w-auto sm:w-1/2 md:w-1/3 mx-auto">
  <h1 class="font-bold text-4xl">New item</h1>

  <%= render "form", item: @item %>

  <%= link_to "Back to items", items_path, class: "fixed inset-x-30 bottom-6 p-4 w-auto sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>
</div>

app/views/items/show.html.erb
<% content_for :title, "Showing item" %>

<div class="w-full">
<div class="w-auto sm:w-1/2 md:w-1/3 mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% if @item.item_cover.attached? %>
    <%= image_tag @item.item_cover.variant(:full).processed %>
  <% end %>
  <%= render @item %>

  <%= link_to "Edit this item", edit_item_path(@item), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to items", items_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this item", @item, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Garbgab App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/pre_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

  <%= f.input :event %>

<h4>Select Items:</h4>
<div class="image-grid">
  <% current_user.items.each do |item| %>
    <% if item.item_cover.attached? %>
      <a>
        <%= f.check_box :item_ids, { multiple: true, include_hidden: false }, item.id, nil%>
        <%= image_tag item.item_cover.variant(:wardrobe).processed%>
      </a>
    <% end %>
    <br>
  <% end %>
</div>
  <%= f.input :description %>

  <div class="form-actions">
    <%= f.button :submit, "Post", class: "rounded-lg" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="w-full">
<div class="w-auto sm:w-1/2 md:w-1/3 mx-auto">
<div class= "flex justify-center mt-1">
<h1 class= "text-4xl underline">Gabs</h1>
</div>
<br>
<div id="posts", class="mb-20">
  <div class="flex justify-between items-center">
    <%= link_to "New post", new_post_path, class: " text-center fixed inset-x-30 bottom-6 p-4 w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>
  <% @posts.each do |post| %>
    <article class="bg-white p-6 rounded-xl ring-1 inset-shadow-3xl shadow-lg hover:shadow-xl transition duration-300 ease-in-out">
      <p  class="mb-2 text-3xl line-clamp-3"><%= post.event %></p>
      <hr class="mb-1">
      <%= link_to post_path(post), class: "block" do%>
        <% if post.item_ids.present? %>
          <div style="display: flex; flex-direction: row; gap: 10px;">
            <% post.item_ids.first(3).each do |item_ids| %>
              <%= image_tag Item.find(item_ids).item_cover.variant(:small).processed %>
            <% end %>
          </div>
        <% else %>
          <p>No images attached.</p>
        <% end %>
        <hr class="mt-1">
        <p  class="text-gray-600 mb-4 line-clamp-3"><%= post.description.truncate(100) %></p>
        <small>Posted on: <%= post.created_at.strftime("%B %d, %Y") %></small>
      <% end %>
    </article>
    <br>
  <% end %>
</div>
</div>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New Post" %>

<div class="w-full">
<div class="w-auto sm:w-1/2 md:w-1/3 mx-auto">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>
</div>

app/views/posts/show.html.erb
<div class="w-full">
<div class="w-auto sm:w-1/2 mx-auto">
<p id="notice"><%= notice %></p>
<% if @post.user == current_user %>
  <div class= "ml-0 text-red-600 hover:text-red-950"><%= button_to "delete", @post, method: :delete %></div>
<% end %>
<h1 class= "text-7xl" ><%= @post.event %></h1><br>
<% if @post.item_ids.present? %>
  <div style="display: flex;  flex-direction: row; gap: 10px;">
    <% @post.item_ids.first(3).each do |item_ids| %>
      <%= image_tag Item.find(item_ids).item_cover.variant(:full).processed %>
    <% end %>
  </div>
  <br>
<% else %>
  <p>No images attached.</p><br>
<% end %>
<p class= "text-4xl"><%= @post.description %></p>
<hr  class="w-48 h-1 mx-auto my-4 bg-neutral-quaternary border-0 rounded-sm md:my-10">
<div id="comments", class="mb-20">
  <h2>Comments</h2>
  <%= render 'comments/form', comment: @comment, board: @board %>
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <table class="table">
          <tbody id="table-comment">
            <%= render @comments %>
          </tbody>
        </table>
      </div>
    </div>
</div>
<%= link_to "Back to posts", posts_path, class: "fixed inset-x-30 bottom-6 p-4 w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='mt-10 col-sm-6 col-12'>
        <div class='copyright'>
          <p>Work-in-progress © 2026. GarbGAB</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-gray-200 shadow-md">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Logo -->
      <nav class="shrink-0 flex items-center">
        <a href="/" class="text-2xl font-bold text-violet-700">GarbGAB</a>
      </nav>
      <!-- Navigation Links (Desktop) -->
      <nav class="hidden sm:flex space-x-40">
        <a class="text-gray-900 hover:text-violet-700 px-3 py-2 rounded-md text-lg font-medium"><%= button_to "Posts(Gab)", posts_path ,method: :get%></a>
        <a class="text-gray-900 hover:text-violet-700 px-3 py-2 rounded-md text-lg font-medium"><%= button_to "Wardrobe(Garb)", items_path, method: :get%></a>
      </nav>
      <nav class="flex space-x-40">
        <%= render 'shared/header_icon' %>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_header_icon.html.erb
<button id="dropdownAvatarNameButton" data-dropdown-toggle="dropdownAvatarName" class="flex mr-0 items-center text-md pe-1 font-medium text-heading rounded-full hover:text-fg-brand md:me-0 focus:ring-4 focus:ring-neutral-tertiary" type="button">
  <span class="sr-only">Open user menu</span>
    <p style="margin-right: 10px;"><%=current_user.name%> </p>
    <%= user_avatar(current_user) %>
  <svg class="w-4 h-4 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 9-7 7-7-7"/></svg>
</button>

<!-- Dropdown menu -->
<div id="dropdownAvatarName" class="z-10 hidden bg-black/40 border-default-medium rounded-base shadow-lg w-35">
    <ul class="px-2 pb-2 text-sm text-blue-800 font-medium" aria-labelledby="dropdownAvatarNameButton">
        <%= button_to(edit_user_registration_path, method: :get, class: "w-full") do%>
          <a class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded">
            <svg class="w-4 h-4 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-width="2" d="M7 17v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3Zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/></svg>
            Edit Profile
          </a>
        <% end %>
        <%= button_to(destroy_user_session_path, method: :delete, class: "w-full") do%>
          <a class="inline-flex items-center w-full p-2 text-fg-danger hover:bg-neutral-tertiary-medium rounded">
            <svg class="w-4 h-4 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H8m12 0-4 4m4-4-4-4M9 4H7a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h2"/></svg>
            Sign out
          </a>
        <% end %>
    </ul>
</div>

app/views/shared/_pre_login_header.html.erb
<header class="bg-gray-200 shadow-md">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Logo -->
      <nav class="shrink-0 flex items-center">
        <a href="/" class="text-2xl font-bold text-violet-700">GarbGAB</a>
      </nav>
      <!-- Navigation Links (Desktop) -->
      <nav class="justify-end-safe">
        <a class="text-gray-900 hover:text-violet-700 px-3 py-2 rounded-md text-sm font-medium"><%= link_to "Register", new_user_registration_path %></a>
        <a class="text-gray-900 hover:text-violet-700 px-3 py-2 rounded-md text-sm font-medium"><%= link_to "Login", new_user_session_path %></a>
      </nav>
    </div>
  </div>
</header>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", "#" %><br />
  <%#new_password_path(resource_name)%>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>